import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API = os.getenv("OPENAI_API")
PDF_FILE_NAME = os.getenv("PDF_FILE_NAME")
ARTICLE_SEARCH_QUERY = os.getenv("ARTICLE_SEARCH_QUERY")
DOWNLOADED_LINKS_FILE = os.getenv("DOWNLOADED_LINKS_FILE")
GPT_MODEL = os.getenv("GPT_MODEL")
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY")
VIDEOS_FOLDER = os.getenv("VIDEOS_FOLDER")
ELEVEN_LABS_KEY = os.getenv("ELEVEN_LABS_KEY")
REPLICATE_API_TOKEN=os.getenv("REPLICATE_API_TOKEN")
TELEGRAM_BOT_TOKEN=os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID=os.getenv("TELEGRAM_CHAT_ID")
